DROP TABLE IF EXISTS TOKENS;
DROP TABLE IF EXISTS PLANNED_ON;
DROP TABLE IF EXISTS PLAYS;
DROP TABLE IF EXISTS FEATURES;
DROP TABLE IF EXISTS ATTENDS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS SCENES;
DROP TABLE IF EXISTS PRACTICES;


CREATE TABLE USERS(
  UserID INT AUTO_INCREMENT NOT NULL,
  Name VARCHAR (32) NOT NULL,
  Mail VARCHAR (64) UNIQUE NOT NULL,
  Password CHAR (60) NOT NULL,
  Admin BOOLEAN DEFAULT 0,
  Informal BOOLEAN DEFAULT 0,
  PRIMARY KEY (UserID)
);

CREATE TABLE ROLES(
  RoleID INT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(32) NOT NULL,
  Description VARCHAR(512),
  PRIMARY KEY (RoleID)
);

CREATE TABLE SCENES(
  SceneID INT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(32) NOT NULL,
  Description VARCHAR(512),
  Sequence INT UNIQUE NOT NULL,
  Last_practiced DATE,
  PRIMARY KEY (SceneID)
);

CREATE TABLE PRACTICES(
  PracticeID INT AUTO_INCREMENT NOT NULL,
  Title VARCHAR(32),
  Start DATETIME,
  PRIMARY KEY (PracticeID)
);

CREATE TABLE PLAYS(
  PlaysID INT AUTO_INCREMENT NOT NULL,
  UserID INT NOT NULL,
  RoleID INT NOT NULL,
  PRIMARY KEY (PlaysID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID),
  FOREIGN KEY (RoleID) REFERENCES ROLES(RoleID)
);

CREATE TABLE FEATURES(
  FeatureID INT AUTO_INCREMENT NOT NULL,
  SceneID INT NOT NULL,
  RoleID INT NOT NULL,
  Mandatory BOOLEAN DEFAULT 1,
  PRIMARY KEY (FeatureID),
  FOREIGN KEY (SceneID) REFERENCES SCENES(SceneID),
  FOREIGN KEY (RoleID) REFERENCES ROLES(RoleID)
);

CREATE TABLE ATTENDS(
  AttendsID INT AUTO_INCREMENT NOT NULL,
  PracticeID INT NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (AttendsID),
  FOREIGN KEY (PracticeID) REFERENCES PRACTICES(PracticeID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE TABLE PLANNED_ON(
  PlanID INT AUTO_INCREMENT NOT NULL,
  PracticeID INT NOT NULL,
  SceneID INT NOT NULL,
  PRIMARY KEY (PlanID),
  FOREIGN KEY (PracticeID) REFERENCES PRACTICES(PracticeID),
  FOREIGN KEY (SceneID) REFERENCES SCENES(SceneID)
);

CREATE TABLE TOKENS(
  TokenID INT AUTO_INCREMENT NOT NULL,
  UserID INT NOT NULL,
  Password CHAR(60) NOT NULL,
  Selector CHAR(60) NOT NULL,
  Expires DATETIME NOT NULL,
  PRIMARY KEY (TokenID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID),
  INDEX (Selector)
);

CREATE TABLE POLLS(
  PollID INT AUTO_INCREMENT NOT NULL,
  Start DATE NOT NULL,
  Duration INT NOT NULL,
  Description VARCHAR(512),
  PRIMARY KEY (PollID)
);

CREATE TABLE POLL_ENTRIES(
  EntryID INT AUTO_INCREMENT NOT NULL,
  PollID INT NOT NULL,
  UserID INT NOT NULL,
  Entries INT NOT NULL,
  PRIMARY KEY (EntryID),
  FOREIGN KEY (PollID) REFERENCES POLLS(PollID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
